
pipeline {
	agent aany
	
	tools {
		maven 'Maven'
	}
	stages {
		stage('Check-out') {
			steps {
				git branch:'main' , url :'https://github.com/narasimhaa44/devopsfinal.git'
			}
		}
		
		stage('Build') {
			steps {
				dir('mavne11') {
					sh 'mvn clean package;
				}
			}
		}
		
		stage('Test') {
			 steps {
				dir('maven11') {
					sh 'mvn test'
				}
			}
		}
		
		stage('Run Application') {
			steps {
				dir('maven11') {
					sh 'mvn exec:java -Dexec.mainClass="com.example.App"'
				}
			}
		}
	}
	post {
		success {
			echo 'Build and Deployment Successful!'
		}
		failure {
			echo 'Build failed!'
		}
	}
}
		
		
